/* Hearth (v3) design tokens, ported from the web app's globals.css.
   Same names, same hex values, same AA-checked pairs: one brand,
   two runtimes. Dark is the candle-lit den: warm browns, never blue. */

import { Easing, type ViewStyle } from "react-native";

export const palettes = {
  light: {
    background: "#faf6ee",
    foreground: "#2b2118",
    surface: "#fffcf5",
    surface2: "#f3ecdd",
    surface3: "#eae1cd",
    border: "#e6dcc8",
    muted: "#6b5d4f",
    brand: "#b5502f",
    brandStrong: "#9c3f22",
    brandSoft: "#f6e3d7",
    brand2: "#d97742",
    brandFg: "#ffffff",
    brandInk: "#8f3a1f",
    onSolid: "#ffffff",
    accent: "#56682d",
    accentSoft: "#e9edd8",
    success: "#25683f",
    danger: "#b32d2d",
    warning: "#8a5c00",
  },
  dark: {
    background: "#1c1612",
    foreground: "#f2ebe1",
    surface: "#262019",
    surface2: "#322a21",
    surface3: "#3e352a",
    border: "#453b2e",
    muted: "#b3a28e",
    brand: "#e0764b",
    brandStrong: "#cf5f33",
    brandSoft: "#40291c",
    brand2: "#e8955f",
    brandFg: "#2b1408",
    brandInk: "#eda07b",
    onSolid: "#ffffff",
    accent: "#8ba852",
    accentSoft: "#262e1a",
    success: "#4caf7d",
    danger: "#e06060",
    warning: "#d9a13a",
  },
} as const;

export type Palette = { [K in keyof (typeof palettes)["light"]]: string };

/* -------------------------------- hearths -------------------------------- */

/**
 * The eight hearths: Ember plus seven re-litings of it. Every scheme keeps
 * Ember's OKLCH lightness curve and its chroma relationships token for token;
 * only the hue families move. That is what keeps eight schemes feeling like
 * one app: the same warmth, the same soft-wash-to-ink distances, a different
 * fire in the grate. Status colours (success, danger, warning) never move
 * between schemes, so red means the same thing at every hearth.
 *
 * Generated by scratchpad/schemes.py, which also verifies that every scheme
 * passes the same WCAG pairs Ember does (foreground on background at 7:1,
 * muted at 4.5:1, brand ink on its soft wash at 4.5:1, and so on) in both
 * appearances. Do not hand-edit a hex here: change the recipe and re-run,
 * or a scheme will quietly stop being readable.
 *
 * The web app carries the same values as CSS custom properties in
 * src/app/globals.css, keyed by [data-scheme]. A test keeps the two in step.
 */
export type HearthId =
  | "ember"
  | "aggie"
  | "rose"
  | "fern"
  | "tide"
  | "dusk"
  | "honey"
  | "slate";

export const hearthPalettes: Record<
  HearthId,
  { light: Palette; dark: Palette }
> = {
  ember: palettes,
  aggie: {
    light: {
      background: "#f4f7f9",
      foreground: "#202427",
      surface: "#fbfcfe",
      surface2: "#e9edf2",
      surface3: "#dde2e8",
      border: "#d8dee4",
      muted: "#5c6065",
      brand: "#4470c4",
      brandStrong: "#355daa",
      brandSoft: "#dee8f9",
      brand2: "#6593ea",
      brandFg: "#ffffff",
      brandInk: "#30559c",
      onSolid: "#ffffff",
      accent: "#775b15",
      accentSoft: "#f3e9d5",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#161819",
      foreground: "#e9ecf0",
      surface: "#1f2124",
      surface2: "#292c2f",
      surface3: "#34373b",
      border: "#393d41",
      muted: "#a0a6ac",
      brand: "#6393ed",
      brandStrong: "#5082e0",
      brandSoft: "#242f44",
      brand2: "#81abf9",
      brandFg: "#101b2f",
      brandInk: "#90b5f9",
      onSolid: "#ffffff",
      accent: "#bf9530",
      accentSoft: "#332913",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
  rose: {
    light: {
      background: "#fdf4f4",
      foreground: "#2c201f",
      surface: "#fffafa",
      surface2: "#f9e8e8",
      surface3: "#f2dcdb",
      border: "#edd7d6",
      muted: "#6d5b5a",
      brand: "#b64b53",
      brandStrong: "#9d3a43",
      brandSoft: "#f9e1e0",
      brand2: "#dd6e74",
      brandFg: "#ffffff",
      brandInk: "#90353e",
      onSolid: "#ffffff",
      accent: "#864a61",
      accentSoft: "#fbe3eb",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#1c1615",
      foreground: "#f5e9e8",
      surface: "#271f1e",
      surface2: "#342828",
      surface3: "#403333",
      border: "#483838",
      muted: "#b79e9d",
      brand: "#e26f76",
      brandStrong: "#d15861",
      brandSoft: "#422727",
      brand2: "#ef8b8e",
      brandFg: "#2c1213",
      brandInk: "#f1999c",
      onSolid: "#ffffff",
      accent: "#d57b9e",
      accentSoft: "#39232b",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
  fern: {
    light: {
      background: "#f5f7f4",
      foreground: "#22241f",
      surface: "#fbfdfa",
      surface2: "#eaeee7",
      surface3: "#dfe4db",
      border: "#dadfd6",
      muted: "#5d615a",
      brand: "#3b854f",
      brandStrong: "#2b703f",
      brandSoft: "#deebe0",
      brand2: "#5fa870",
      brandFg: "#ffffff",
      brandInk: "#28673a",
      onSolid: "#ffffff",
      accent: "#636423",
      accentSoft: "#ebecd7",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#171815",
      foreground: "#eaede8",
      surface: "#20221e",
      surface2: "#2a2c28",
      surface3: "#353832",
      border: "#3b3e38",
      muted: "#a2a79d",
      brand: "#59a36b",
      brandStrong: "#46995c",
      brandSoft: "#233426",
      brand2: "#7ebe8b",
      brandFg: "#0e1f12",
      brandInk: "#8fc599",
      onSolid: "#ffffff",
      accent: "#a0a242",
      accentSoft: "#2c2c17",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
  tide: {
    light: {
      background: "#f3f7f8",
      foreground: "#1e2426",
      surface: "#f9fdfe",
      surface2: "#e7eef0",
      surface3: "#dae4e6",
      border: "#d5dfe1",
      muted: "#596263",
      brand: "#008796",
      brandStrong: "#007280",
      brandSoft: "#d6ecef",
      brand2: "#00aaba",
      brandFg: "#ffffff",
      brandInk: "#006875",
      onSolid: "#ffffff",
      accent: "#1c6f5d",
      accentSoft: "#d9f1e9",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#151819",
      foreground: "#e8edee",
      surface: "#1e2223",
      surface2: "#272d2e",
      surface3: "#323839",
      border: "#373e40",
      muted: "#9ca8aa",
      brand: "#00a2b2",
      brandStrong: "#009bac",
      brandSoft: "#163538",
      brand2: "#40c0cd",
      brandFg: "#002023",
      brandInk: "#63c7d2",
      onSolid: "#ffffff",
      accent: "#3bb297",
      accentSoft: "#17302a",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
  dusk: {
    light: {
      background: "#f7f6f9",
      foreground: "#242227",
      surface: "#fdfcff",
      surface2: "#edebf2",
      surface3: "#e3e0e9",
      border: "#dedbe5",
      muted: "#615e66",
      brand: "#885da7",
      brandStrong: "#744c8f",
      brandSoft: "#ece3f3",
      brand2: "#ab80cc",
      brandFg: "#ffffff",
      brandInk: "#6a4683",
      onSolid: "#ffffff",
      accent: "#5b598a",
      accentSoft: "#e8e8fb",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#18171a",
      foreground: "#edebf0",
      surface: "#222024",
      surface2: "#2c2b2f",
      surface3: "#37363b",
      border: "#3e3c42",
      muted: "#a6a3ae",
      brand: "#af81d0",
      brandStrong: "#9d6dbf",
      brandSoft: "#352a3c",
      brand2: "#c099dd",
      brandFg: "#201628",
      brandInk: "#c7a6e0",
      onSolid: "#ffffff",
      accent: "#9592db",
      accentSoft: "#29283a",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
  honey: {
    light: {
      background: "#fbf6ef",
      foreground: "#292218",
      surface: "#fffcf6",
      surface2: "#f4ebdf",
      surface3: "#ece0d0",
      border: "#e8dbcb",
      muted: "#685e50",
      brand: "#9f6500",
      brandStrong: "#885300",
      brandSoft: "#f1e5d5",
      brand2: "#c4871e",
      brandFg: "#ffffff",
      brandInk: "#7d4c00",
      onSolid: "#ffffff",
      accent: "#85513a",
      accentSoft: "#fae6dd",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#1a1712",
      foreground: "#f2ebe2",
      surface: "#25201a",
      surface2: "#312a22",
      surface3: "#3d352b",
      border: "#443b2f",
      muted: "#b1a390",
      brand: "#c58814",
      brandStrong: "#b77500",
      brandSoft: "#3b2c18",
      brand2: "#d7a151",
      brandFg: "#261803",
      brandInk: "#dbac6a",
      onSolid: "#ffffff",
      accent: "#d28663",
      accentSoft: "#38261d",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
  slate: {
    light: {
      background: "#f5f7f8",
      foreground: "#212426",
      surface: "#fbfcfe",
      surface2: "#eaedf0",
      surface3: "#dee2e6",
      border: "#d9dee1",
      muted: "#5c6063",
      brand: "#46799c",
      brandStrong: "#376685",
      brandSoft: "#dfe9f0",
      brand2: "#689cc0",
      brandFg: "#ffffff",
      brandInk: "#325d7a",
      onSolid: "#ffffff",
      accent: "#346878",
      accentSoft: "#ddeef4",
      success: "#25683f",
      danger: "#b32d2d",
      warning: "#8a5c00",
    },
    dark: {
      background: "#161819",
      foreground: "#eaecee",
      surface: "#1f2123",
      surface2: "#292c2e",
      surface3: "#343739",
      border: "#3a3d40",
      muted: "#a0a6aa",
      brand: "#659bbe",
      brandStrong: "#538cb3",
      brandSoft: "#25313a",
      brand2: "#85b2d2",
      brandFg: "#111d25",
      brandInk: "#94bbd7",
      onSolid: "#ffffff",
      accent: "#5ba8bf",
      accentSoft: "#1c2e33",
      success: "#4caf7d",
      danger: "#e06060",
      warning: "#d9a13a",
    },
  },
};

/**
 * The picker's order and words, shared by the Look and feel screen and the
 * web appearance page. `hint` finishes the sentence "<Label>, <hint>" in the
 * option's accessibility label, so keep it lowercase and short.
 */
export const HEARTHS: { id: HearthId; label: string; hint: string }[] = [
  { id: "ember", label: "Ember", hint: "the original clay and cream" },
  { id: "aggie", label: "Aggie", hint: "blue and gold, go Ags" },
  { id: "rose", label: "Rose", hint: "soft pink with red embers" },
  { id: "fern", label: "Fern", hint: "greens out of the arboretum" },
  { id: "tide", label: "Tide", hint: "sea glass and deep teal" },
  { id: "dusk", label: "Dusk", hint: "violet, just after sunset" },
  { id: "honey", label: "Honey", hint: "amber and toasted gold" },
  { id: "slate", label: "Slate", hint: "cool blue-grey and quiet" },
];

/** The default: the scheme Hearth has always been. */
export const HEARTH_DEFAULT: HearthId = "ember";

/** True when a value read back from storage names a real hearth. */
export function isHearthId(value: unknown): value is HearthId {
  return (
    typeof value === "string" && HEARTHS.some((hearth) => hearth.id === value)
  );
}

/* ----------------------------- course tints ----------------------------- */

/**
 * The six colours a student can hang on a course, matching the values
 * `enrollments.color` accepts. The name is what we store and what the picker
 * shows; the colours themselves live in `courseTints`.
 *
 * The rule for turning a course into one of these (the student's pick when
 * they made one, a stable hash of the course code when they didn't) lives in
 * `@/lib/course-color`, not here. This file only owns the paint.
 */
export type CourseTint = "ember" | "fern" | "clay" | "plum" | "sky" | "sand";

/**
 * One tint: the wash a course sits on, and the ink that reads on that wash.
 *
 * `soft` is a fill: a chip, a calendar block, the stripe down a card. `ink`
 * is the text and the icons *on* that fill, and it is dark enough in light
 * and bright enough in dark to also work as a standalone mark (a dot, a bar,
 * the course code) on `background`, `surface`, or `surface2`.
 *
 * There is deliberately no saturated third step. A course colour is a label,
 * not a call to action. The ember stays the only thing in the app that fills
 * a button.
 */
export type CourseTintColors = { soft: string; ink: string };

export type CourseTintScale = Record<CourseTint, CourseTintColors>;

/**
 * The course palette, both appearances.
 *
 * **Ember and fern are the brand and accent pairs, unchanged.** A course the
 * student tinted ember is wearing the same clay wash as every brand chip in
 * the app, so a coloured course sits *inside* the hearth rather than beside
 * it. The other four are new, and they are held to the same standard: warm,
 * low chroma, and quiet enough that six of them in a week view read as a
 * calendar rather than a highlighter drawer.
 *
 * How they were tuned:
 *
 * - **Every `ink` on its own `soft` clears 4.5:1** in both themes: 5.15 to
 *   6.05 in light, 5.26 to 7.58 in dark. Ink on `background` and on `surface`
 *   clears it too (5.7 minimum), so the code can be set in its colour on a
 *   plain card.
 * - **The six fills stay apart.** No two `soft` fills in a theme are closer
 *   than ΔE 9.2 (light) or 8.3 (dark) in CIE Lab, so adjacent rows are
 *   distinguishable without reading the label.
 * - **The six fills stay level.** Light fills sit in an L\* band of 89–93 and
 *   dark in 17.6–19.1, so no one course looks heavier than its neighbours.
 * - **A course keeps its identity across themes.** Each tint holds its hue
 *   within a few degrees between light and dark; only the lightness flips.
 *
 * Colour is never the only signal. The course code is always rendered next
 * to the tint, so a student who cannot separate two of these still reads the
 * row correctly.
 */
export const courseTints: { light: CourseTintScale; dark: CourseTintScale } = {
  light: {
    /* The brand pair, verbatim: brandSoft / brandInk. */
    ember: { soft: "#f6e3d7", ink: "#8f3a1f" },
    /* The accent pair, verbatim: accentSoft / accent. */
    fern: { soft: "#e9edd8", ink: "#56682d" },
    /* Unfired rose-brick. Sits opposite ember so the two don't blur. */
    clay: { soft: "#f9d9dc", ink: "#8e3f48" },
    /* Dried plum skin: the one violet, kept greyed. */
    plum: { soft: "#ecdcf1", ink: "#6f4482" },
    /* Faded chambray. The coolest thing we allow, and barely. */
    sky: { soft: "#d3e6eb", ink: "#3b5e6a" },
    /* Wheat and dry grass, one step off the cream page. */
    sand: { soft: "#f2e5c4", ink: "#77591f" },
  },
  dark: {
    ember: { soft: "#40291c", ink: "#eda07b" },
    fern: { soft: "#262e1a", ink: "#8ba852" },
    clay: { soft: "#402326", ink: "#e79fa5" },
    plum: { soft: "#352339", ink: "#cba3d5" },
    sky: { soft: "#1d3035", ink: "#8fc1cb" },
    sand: { soft: "#362d19", ink: "#dabf7c" },
  },
};

/**
 * The course palette for the active appearance. Feed it `useColorScheme()`.
 * Anything that isn't an explicit "dark" falls back to light, the same way
 * `elevationFor` and `useTheme()` do.
 *
 * `const tint = courseTintsFor(scheme)[colorForCourse(enrollment.color, course.code)];`
 */
export function courseTintsFor(
  scheme: "light" | "dark" | "unspecified" | null | undefined
): CourseTintScale {
  return scheme === "dark" ? courseTints.dark : courseTints.light;
}

export const radius = {
  card: 20,
  control: 12,
  full: 999,
} as const;

/* -------------------------------- space --------------------------------- */

/**
 * The spacing ladder: the one token family the system was missing.
 *
 * These are not invented, and they are not derived from a formula. Four of
 * them are structural facts already load-bearing in the app (`Card` pads by
 * 16, `Screen` gutters by 20 and ends at 32, `SectionLabel` puts 24 above
 * itself), and the small end is what roughly fifteen hundred hand-written
 * paddings had already converged on: 12 and 10 carry most of the app, with
 * 8 / 6 / 4 inside small things. The values that appeared a handful of times
 * each (3, 5, 7, 9, 14, 18) are the drift this ladder exists to stop.
 *
 * Names describe the RELATIONSHIP, not the size, so a screen reads as an
 * argument about hierarchy rather than a pile of numbers:
 *
 * - `hair` (2): a nudge. Optical alignment, the gap under a label.
 * - `tight` (4): parts of one thing, an icon and its count.
 * - `snug` (6): a chip's inner padding, a two-line stack.
 * - `cosy` (8): the default gap between siblings in a row.
 * - `room` (10): a list row's vertical breathing.
 * - `close` (12): between rows in a group, between the parts of a card.
 * - `card` (16): `Card`'s own padding, and the gap between cards.
 * - `gutter` (20): the screen's left and right margin. Every screen.
 * - `chapter` (24): above a `SectionLabel`.
 * - `rest` (32): the bottom of a scroll, and the air around an empty state.
 *
 * **Comfort is mostly this.** The palette makes Hearth warm; the spacing makes
 * it unhurried. When a screen feels cramped the fix is almost never a colour.
 * It is `cosy` where the content wanted `gutter`. Reach one rung wider than
 * feels necessary, especially around anything a student reads rather than
 * scans.
 *
 * Not a hard rule for one-off optical fixes: a 3px nudge to line a glyph up
 * with a baseline is a real thing and should stay 3, with a comment. It is a
 * rule for anything structural.
 */
export const space = {
  hair: 2,
  tight: 4,
  snug: 6,
  cosy: 8,
  room: 10,
  close: 12,
  card: 16,
  gutter: 20,
  chapter: 24,
  rest: 32,
} as const;

export type Space = keyof typeof space;

export const fonts = {
  /* Loaded in the root layout via @expo-google-fonts. */
  display: "BricolageGrotesque_700Bold",
  displaySemi: "BricolageGrotesque_600SemiBold",
  body: "PlusJakartaSans_400Regular",
  bodyMedium: "PlusJakartaSans_500Medium",
  bodySemi: "PlusJakartaSans_600SemiBold",
  bodyBold: "PlusJakartaSans_700Bold",
} as const;

/* ------------------------------ elevation ------------------------------ */

/** The three rungs of the shadow ladder. */
export type ElevationStep = "rest" | "raised" | "floating";

export type ElevationScale = Record<ElevationStep, ViewStyle>;

/* Shadows in the hearth world are warm: they read as lamplight falling
   past a real object, not as a grey drop-shadow from a spec sheet. Both
   inks come out of the palette rather than a one-off literal: espresso
   foreground in light, the deepest candle-brown we own in dark. */
const shadowInk = {
  light: palettes.light.foreground,
  dark: palettes.dark.background,
} as const;

/**
 * Warm, low-contrast shadow scale: three steps, both appearances.
 *
 * - `rest` for cards sitting on the page. This is the default for `Card`
 *   and should cover nine surfaces in ten.
 * - `raised` for something the user lifted off the page: a menu, a popover,
 *   a row that is mid-drag, a floating compose button.
 * - `floating` for the top of the stack: bottom sheets and modals, the one
 *   thing on screen while it is open.
 *
 * Dark mode leans on **surface contrast**, not shadow. A brown shadow on a
 * candle-dark background is nearly invisible, and cranking the opacity to
 * make it show reads as soot. So the dark values are deliberately softer
 * (`rest` drops the Android elevation to zero entirely), and depth in the
 * dark theme comes from `surface` / `surface2` / `surface3` stepping up
 * away from `background` plus the hairline `border`.
 *
 * Spread a step straight into a style object:
 * `style={{ ...elevationFor(scheme).raised, backgroundColor: theme.surface }}`
 */
export const elevation: { light: ElevationScale; dark: ElevationScale } = {
  light: {
    rest: {
      shadowColor: shadowInk.light,
      shadowOpacity: 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    raised: {
      shadowColor: shadowInk.light,
      shadowOpacity: 0.1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    floating: {
      shadowColor: shadowInk.light,
      shadowOpacity: 0.16,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 14 },
      elevation: 10,
    },
  },
  dark: {
    rest: {
      shadowColor: shadowInk.dark,
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 0,
    },
    raised: {
      shadowColor: shadowInk.dark,
      shadowOpacity: 0.14,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 5 },
      elevation: 3,
    },
    floating: {
      shadowColor: shadowInk.dark,
      shadowOpacity: 0.22,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
  },
};

/**
 * The elevation set for the active appearance. Feed it `useColorScheme()`.
 * Anything that isn't an explicit "dark" (null, undefined, the
 * "unspecified" scheme before the system has answered) falls back to
 * light, the same way `useTheme()` does.
 */
export function elevationFor(
  scheme: "light" | "dark" | "unspecified" | null | undefined
): ElevationScale {
  return scheme === "dark" ? elevation.dark : elevation.light;
}

/* -------------------------------- motion -------------------------------- */

/**
 * Durations in milliseconds, and the three curves they travel along. Four
 * durations and three easings. That is the whole budget.
 *
 * - `instant` (0): the reduced-motion value. Pass it as the duration
 *   instead of branching around the animation, so state still lands.
 * - `quick` (140): press feedback, a chip selecting, a checkbox filling.
 *   Fast enough to feel like a direct consequence of the finger.
 * - `base` (240): the house default. Sheets, expanding cards, list rows
 *   settling in, anything that "arrives".
 * - `slow` (320): full-screen transitions and the skeleton pulse. Rare.
 *
 * **House easing** lives in `motion.easing`, so nothing has to reach for
 * `react-native`'s `Easing` and invent a fourth curve:
 *
 * - `standard` (`inOut` cubic) is for anything **reversible**: press in and out,
 *   open and close, select and deselect. It leaves and returns along the
 *   same curve, so the undo feels like the same gesture backwards. When you
 *   are not sure, this is the one.
 * - `enter` (`out` cubic) is for **arrivals.** Something appearing that will not
 *   immediately leave: a newly inserted row, a card landing on a first
 *   paint, a button settling back under a lifted finger. Fast off the mark,
 *   slow into place.
 * - `exit` (`in` cubic) is for **departures.** Something on its way out: a
 *   dismissed sheet, a row being removed. Slow to let go, then gone. Never
 *   use it for something arriving; an arrival that accelerates away from
 *   you reads as a glitch.
 *
 * Arrivals and departures are asymmetric on purpose. A thing takes its time
 * settling in and leaves without lingering, which is roughly how objects
 * behave and exactly how a press should feel: quick in, slower out.
 *
 * **The rule: motion is for arrival and completion, never decoration.**
 * Animate a thing that just appeared, or a thing the user just finished.
 * Nothing loops, nothing bounces to get noticed, nothing moves because the
 * screen would otherwise be still. If you cannot name the moment the
 * animation is reporting, delete it.
 *
 * **And every animation is gated on `useReducedMotion()`.** Not "animate
 * less": land the final state in `motion.instant`. A primitive that cannot
 * be turned off this way is not finished.
 */
export const motion = {
  instant: 0,
  quick: 140,
  base: 240,
  slow: 320,
  easing: {
    standard: Easing.inOut(Easing.cubic),
    enter: Easing.out(Easing.cubic),
    exit: Easing.in(Easing.cubic),
  },
} as const;
